options:
  logging: CLOUD_LOGGING_ONLY

steps:

  - name: 'gcr.io/cloud-builders/gcloud'
    id: Fetch .env File
    entrypoint: bash
    args:
      - '-c'
      - |
        mkdir -p /workspace/app
        gcloud secrets versions access latest --secret=mentalq-backend-env > /workspace/app/.env

  - name: 'gcr.io/cloud-builders/docker'
    id: Build Docker Image
    args: [
      'build',
      '--build-arg', 'mentalq-backend-env_PATH=/workspace/app/.env',
      '-t', 'asia-southeast2-docker.pkg.dev/mentalq-cloud/mentalq-backend/backend-api',
      '.'
    ]


  - name: 'gcr.io/cloud-builders/docker'
    id: Push Docker Image
    args: [
      'push',
      'asia-southeast2-docker.pkg.dev/mentalq-cloud/mentalq-backend/backend-api'
    ]

  # Step 5: Deploy the image to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    id: Deploy to Cloud Run
    args: [
      'run',
      'deploy',
      'mentalq-backend',
      '--image',
      'asia-southeast2-docker.pkg.dev/mentalq-cloud/mentalq-backend/backend-api',
      '--region',
      'asia-southeast2',
      '--platform',
      'managed',
      '--allow-unauthenticated',
      '--port=8080',
      '--timeout',
      '600s',
      '--memory',
      '4Gi',
    ]

images:
  - 'asia-southeast2-docker.pkg.dev/mentalq-cloud/mentalq-backend/backend-api'
