options:
  logging: CLOUD_LOGGING_ONLY

steps:

 - name: 'gcr.io/cloud-builders/gcloud'
    id: Fetch .env File
    entrypoint: bash
    args:
      - '-c'
      - |
        gcloud secrets versions access latest --secret=mentalq-backend-env > /app/.env

  # Step 2: Copy the .env file into the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    id: Build Docker Image
    args: [
      'build',
      '--build-arg', 'mentalq-backend-env_PATH=/app/.env',
      '-t', 'asia-southeast2-docker.pkg.dev/mentalq-cloud/mentalq-backend/backend-api',
      '.'
    ]
  # Step 1: Pull the Node.js base image and install dependencies
  - name: 'node:18-alpine'
    id: Install Dependencies
    entrypoint: npm
    args: ['install']

  # Step 3: Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    id: Build Docker Image
    args: [
      'build',
      '-t',
      'asia-southeast2-docker.pkg.dev/mentalq-cloud/mentalq-backend/backend-api',
      '.'
    ]

  # Step 4: Push the Docker image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    id: Push Docker Image
    args: [
      'push',
      'asia-southeast2-docker.pkg.dev/mentalq-cloud/mentalq-backend/backend-api'
    ]

  # Step 5: Deploy the image to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    id: Deploy to Cloud Run
    args: [
      'run',
      'deploy',
      'your-app-service',
      '--image',
      'asia-southeast2-docker.pkg.dev/mentalq-cloud/mentalq-backend/backend-api',
      '--region',
      'us-central1',
      '--platform',
      'managed',
      '--allow-unauthenticated'
    ]

images:
  - 'asia-southeast2-docker.pkg.dev/mentalq-cloud/mentalq-backend/backend-api'
